- src/App.tsx
- src/components/Common/Header.tsx
- src/styles/Header_Footer/header.scss
header 레이아웃 중간저장을 위하여 커밋하였습니다. 브랜치는 계속 유지하여 작업하겠습니다.
> Design: header 레이아웃 중간저장

- src/global.scss
- src/layouts/CommonLayout.tsx
- src/pages/MainPage.tsx
> Design: commonLayout 디자인 수정

- public/image/modal_close_icon.svg
- src/Common.tsx
- src/components/IconButton/IconBtn.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/ModalContent1.tsx
- src/components/Modal/ModalContent2.tsx
- src/config/code.ts
- src/store/modalStore.ts
- src/styles/common.scss
- src/styles/header.scss
#45 
공통 모달창 UI작업
공통 모달창 전역상태관리 store 추가
공통 뱃지 백그라운드 컬러 props 추가
header css z-index: 9999 -> 10으로 변경
#45 
어떤 변경 사항이 있나요?
> Design: 공통 모달창 UI작업

- src/Common.tsx
- src/components/Input/Input.tsx
- src/components/Input/NumberInput.tsx
- src/components/Modal/Modal.tsx
- src/config/code.ts
- src/styles/ChatPage/chatPage.scss
- src/styles/common.scss
- src/uiComponents/ChatPage/ExpertWrapper.tsx
- src/uiComponents/ChatPage/Modal/DealModal.tsx
#47 
공통 모달 푸터 영역 추가(버튼 생성)
공통 인풋 value 작성영역 추가
공통 인풋 type=number 파일 새로 작업
공통 인풋 type=number 숫자 입력시 단위별 콤마 자동 설정
chatRoom페이지 거래 요청 모달 추가
#47 
어떤 변경 사항이 있나요?
> Refactor: 공통 모달/인풋 수정

- src/App.tsx
- src/components/Footer/Footer.tsx
- src/pages/Policy.tsx
- src/styles/footer.scss
- src/styles/variables.scss
#15 
- 1차 레이아웃 완료
- 이용약관 및 개인정보 처리방침 링크 연결
- 카카오톡 상담 연결
- 이용약관 및 개인정보 처리방침 페이지 연결
- kakao / naver 컬러를 사용할수 있게 변수 추가
Close #15 
어떤 변경 사항이 있나요?
> Design : footer 레이아웃 1차완성 및 페이지링크수정

- src/Common.tsx
- src/components/PageTitle/PageTitle.tsx
- src/config/code.ts
- src/pages/ChatPage.tsx
- src/styles/ChatPage/chatPage.scss
- src/styles/common.scss
#52 
페이지 타이틀 공통 작업
이전페이지 이동 버튼 및 링크 props 추가
#52 
어떤 변경 사항이 있나요?
> Design: 페이지 타이틀 공통 작업

- package-lock.json
- package.json
- src/App.tsx
- src/pages/ExpertProfileEditPage.tsx
- src/styles/ExpertProfileEditPage/career.scss
- src/styles/ExpertProfileEditPage/location.scss
- src/styles/ExpertProfileEditPage/main.scss
- src/styles/ExpertProfileEditPage/service.scss
- src/uiComponents/ExpertProfileEditPage/CareerModal.tsx
- src/uiComponents/ExpertProfileEditPage/LocationModal.tsx
- src/uiComponents/ExpertProfileEditPage/ServiceModal.tsx
#38 
전문가 프로필 페이지, 모달 레이아웃
Close #38 
어떤 변경 사항이 있나요?
> Design: 전문가 프로필 페이지 레이아웃

- src/pages/MyPage.tsx
- src/styles/MyPage/main.scss
#56
- 마이페이지 title 공통 ui로 변경
- scss 디테일 수정
Close #56
어떤 변경 사항이 있나요?
> Design: 마이페이지 title 공통 UI로 변경

- src/App.tsx
- src/components/Header/Header.tsx
- src/pages/UserEstimationPage.tsx
- src/styles/UserEstimationPage/userEstimation.scss
#39 
- 1차레이아웃 완성 및 페이지 연결
- 캘린더, 지역선택, 시간선택부분을 제외한 레이아웃 변경
- 견적요청서 페이지 연결
close #39 
어떤 변경 사항이 있나요?
> Design : UserEstimationPage 1차레이아웃 완성 및 페이지 연결

- package-lock.json
#64 
패키지 설치 도중에 보안관련 경고가 떠 급하게 수정하였습니다.
- @eslint/plugin-kit 패키지에서 높은 심각도의 보안 취약점이 발견
- 이 문제는 ReDoS (Regular Expression Denial of Service)와 관련이 있으며, 이를 해결하기 위해 업데이트가 필요
Close #64 
어떤 변경 사항이 있나요?
> Fix : 패키지 보안 관련 수정

- src/styles/MainPage/main.scss
- src/uiComponents/MainPage/TabContentType1.tsx
- src/uiComponents/MainPage/TabContentType2.tsx
> Design : MainPage UI 세부 수정

- src/pages/MainPage.tsx
- src/styles/MainPage/main.scss
- src/uiComponents/MainPage/Arrow.tsx
> Design : 메인 페이지 레이아웃 세부 조정 중

- src/config/server.ts
- src/global.scss
- src/uiComponents/ChatPage/ChatRoom.tsx
#73 
채팅 임시 서버 주석 처리
global html font-size 미디어 쿼리 작업
#73 
어떤 변경 사항이 있나요?
> Fix: 채팅 임시 서버 주석 처리

- package-lock.json
- src/components/Footer/Footer.tsx
- src/components/Header/Header.tsx
- src/pages/UserEstimationPage.tsx
- src/styles/UserEstimationPage/userEstimation.scss
- src/styles/footer.scss
- src/styles/header.scss
#15 #16 #39 
- 주석삭제
- 로그인버튼-로그인페이지 연결
- 전반적인 레이아웃 수정
- 내용추가
- 이용약관 개인정보처리방침 노션페이지로 연결
- 전반적인 레이아웃 수정
- 주석추가 및 레이아웃 클래스 수정
- 스타일 주석 추가
close #15 #16 #39  
어떤 변경 사항이 있나요?
> Design : Header,Footer,userEstimation layout수정

- public/image/checkbox_checked.svg
- public/image/radio.svg
- public/image/radio_checked.svg
- public/image/radio_checked_disabled.svg
- public/image/radio_disabled.svg
- public/image/select_arrow_icon.svg
- src/Common.tsx
- src/components/Select/Select.tsx
- src/config/code.ts
- src/pages/ChatListPage.tsx
- src/styles/ChatListPage/chatListPage.scss
- src/styles/ChatPage/chatPage.scss
- src/styles/common.scss
#79 
공통 셀렉트박스 작업
체크박스/라디오 이미지 변경
textarea 배경색 변경
채팅 페이지 수정
#79 
어떤 변경 사항이 있나요?
> Feat: 공통 셀렉트박스 생성

- package-lock.json
- public/mockServiceWorker.js
- src/components/Badge/ProfileBadge.tsx
- src/pages/Estimationpage.tsx
- src/pages/ExpertProfileModal.tsx
- src/styles/Estimationpage/estimation.scss
- src/styles/starrating.scss
> Design:받은견적,프로필벳지 수정

- src/main.tsx
- src/utils/backPrevent.tsx
- src/utils/scrollToTop.tsx
#77 
- 뒤로가기 기능을 막는 커스텀 훅입니다.
(커밋하고보니 파일명이 커스텀훅이름이랑 일치하지 않는군요 추후에 수정하겠습니다.)
- 뒤로가기 버튼을 누를경우 알림창이 뜨고 메인페이지로 이동합니다.
- useBackPrevent() 로 함수처럼 꺼내서 사용하시면 됩니다.
- 페이지 이동시 스크롤을 최상단에 위치하게 만드는 컴포넌트입니다.
- 컴포넌트로 작성되었습니다.
- scrollToTop을 적용하여 모든페이지에 적용되게 만들었습니다.
Close #77 
어떤 변경 사항이 있나요?
> Feat : scrollToTop, backPrevent 기능 추가

- package-lock.json
- src/Common.tsx
- src/components/Badge/ProfileBadge.tsx
- src/config/server.ts
- src/pages/ChatListPage.tsx
- src/styles/ChatListPage/chatListPage.scss
- src/styles/ChatPage/chatPage.scss
- src/styles/common.scss
- src/styles/variables.scss
- src/uiComponents/ChatListPage/AllChats.tsx
- src/uiComponents/ChatListPage/CompletedChats.tsx
- src/uiComponents/ChatListPage/OngoingChats.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
#91 
채팅리스트 페이지 수정
채팅리스트 페이지 컴포넌트 분할
공통 뱃지 수정
#91 
어떤 변경 사항이 있나요?
> Refactor: 채팅 페이지 수정

- src/pages/ExpertModal.tsx
- src/pages/Expertlistpage.tsx
- src/styles/Estimationpage/estimation.scss
- src/styles/Estimationpage/expertprofile.scss
- src/styles/Expertlistpage/expertModal.scss
> Desing:받은요청리스트 페이지- 견적서 보내기 모달

- src/config/server.ts
- src/pages/ChatListPage.tsx
- src/styles/ChatListPage/chatListPage.scss
#100 
채팅리스트 페이지 디자인 변경
server.ts 충돌 해결
#100 
어떤 변경 사항이 있나요?
> Design: 채팅리스트 페이지 디자인 변경

- src/App.tsx
- src/pages/MyPage.tsx
- src/pages/Reservation.tsx
- src/styles/MyPage/main.scss
- src/uiComponents/MyPage/ReservationSection.tsx
#102 
- routes 변경
- 예약페이지 연결
- 레이아웃 변경
- 예약내역 페이지 연결
- ReservationSection 컴포넌트 생성후 삽입
Close #102 
어떤 변경 사항이 있나요?
- [X] 새로운 기능 추가
> Design : MyPage 레이아웃변경 및 예약리스트 링크추가

- src/global.scss
- src/pages/ChatPage.tsx
- src/styles/ChatListPage/chatListPage.scss
- src/styles/ChatPage/chatPage.scss
- src/styles/Estimationpage/estimation.scss
- src/styles/Expertlistpage/expertlistpage.scss
- src/styles/variables.scss
- src/uiComponents/ChatListPage/Chat.tsx
- src/uiComponents/ChatPage/ExpertWrapper.tsx
#104 
채팅 페이지 반응형 작업
#104 
어떤 변경 사항이 있나요?
> Design: 채팅페이지 반응형 작업

- src/pages/Estimationlistpage.tsx
- src/pages/Expertlistpage.tsx
- src/store/expertListStore.ts
- src/uiComponents/ExpertProfileEditPage/ExpertModal.tsx
> Feat:받은요청,받은견적-채팅방연결,견적서보내기 모달 전역상태

- src/api/apiClient.ts
- src/pages/CallbackPage.tsx
- src/pages/LoginPage.tsx
#34,#35,#36
중복되는 로직을 간소화함.
close #34 #35 #36 
어떤 변경 사항이 있나요?
> Refactor : 로그인 요청 로직 간소화

- src/App.tsx
- src/pages/MyPage.tsx
- src/pages/Reservation.tsx
- src/pages/ReservationPage.tsx
- src/styles/MyPage/main.scss
- src/styles/ReservationPage/Reservation.scss
- src/uiComponents/MyPage/ReservationList/UserReview.tsx
#84 
- Reservation -> ReservationPage로 수정
- 유저예약페이지 레이아웃 및 컴포넌트 작성중 중간저장
- 유저리뷰파트 모달부분 추가
어떤 변경 사항이 있나요?
> Design : 유저리뷰페이지 중간저장

- src/components/Badge/ProfileBadge.tsx
- src/components/LodingSpinner/LodingSpinner.tsx
- src/styles/lodingspinner.scss
> Design: 공통 로딩스피닝

- package-lock.json
- package.json
> Chore : js_cookie 라이브러리 삭제

- src/api/client.ts
- src/pages/CallbackPage.tsx
#119 
axios post 오류로 인한 수정의 일환으로 auth 인스턴스 생성
close #119 
어떤 변경 사항이 있나요?
> Fix : axios auth 인스턴스 생성

- src/pages/CallbackPage.tsx
로그인 시 provider에 따른 state 분기 처리
어떤 변경 사항이 있나요?
> Fix : 로그인 시 provider에 따른 state 분기 처리

- src/api/client.ts
- src/pages/CallbackPage.tsx
- src/pages/LoginPage.tsx
- src/pages/MainPage.tsx
- src/styles/LoginPage/login.scss
- src/styles/MainPage/main.scss
- src/uiComponents/MainPage/Filming.tsx
- src/uiComponents/MainPage/Singer.tsx
- src/uiComponents/MainPage/Snapshot.tsx
- src/uiComponents/MainPage/WeddingMC.tsx
#12 #13 
로그인, 메인 페이지 디자인 변경에 따른 css 변경
closes #12 closes #14 
어떤 변경 사항이 있나요?
> Design : 로그인, 메인 페이지 CSS 변경

- src/api/experts.ts
- src/config/dummy.ts
- src/config/types.ts
- src/mocks/handlers.ts
- src/pages/ExpertProfileEditPage.tsx
- src/uiComponents/ExpertProfileEditPage/ServiceModal.tsx
#116
- 프로필 편집 페이지를 위한 patch api mocking 구현
- patch method를 쓰기 위해서 expertId가 필요해서 기존 post api에서 id를 추가함
- post api를 요청하면 get api가 요청되면서 프로필이 저장된 것을 확인할 수 있음
- expertId가 true가 되면서 프로필 등록 -> 프로필 편집으로 바뀜
Close #116 
어떤 변경 사항이 있나요?
> Test: 전문가 프로필 수정 페이지 patch api mocking 구현

- src/App.tsx
- src/config/types.ts
- src/global.scss
- src/layouts/ToastLayout.tsx
- src/pages/ExpertProfileEditPage.tsx
- src/store/toastStore.ts
- src/styles/toastMessage.scss
- src/uiComponents/ExpertProfileEditPage/CareerModal.tsx
- src/uiComponents/ExpertProfileEditPage/LocationModal.tsx
- src/uiComponents/ExpertProfileEditPage/LocationSection.tsx
- src/utils/ToastMessage.tsx
#125
- toast 직접 구현
- 전역 관리 및 ToastLayout.tsx로 최상위에 라우트 연결, toast css 구현
- 기존 전문가 프로필 페이지에 있던 alert 기능 -> toast로 바꿈
- ex) const { addToasts } = useToastStore();
- ex) addToasts({ type: 'success', title: '프로필이 수정되었습니다.', id: Date.now().toString() });
- 이 코드를 넣으면 toast 기능 확인 가능
Close #125
어떤 변경 사항이 있나요?
> Feat: Toast 기능 추가

- src/store/toastStore.ts
#137
- 기존 로직엔 버튼 여러번 누르면 toast message가 여러 개 나왔음
- 수정된 로직엔 버튼 여러번 눌러도 한 번만 나오게 변경
Close #137
어떤 변경 사항이 있나요?
> Feat: 토스트 message 여러번 뜨는거 방지

- src/pages/CallbackPage.tsx
- src/pages/LoginPage.tsx
#89 
코드 리팩토링 이후로 로그인 페이지 진입 시 팝업창 뜨는 이슈 있어서 해당 부분 수정함.
어떤 변경 사항이 있나요?
> Fix : 로그인 페이지 진입 시 팝업창 뜨는 오류 수정

- src/Common.tsx
- src/components/Confirm/Confirm.tsx
- src/config/code.ts
- src/store/confirmStore.ts
- src/styles/common.scss
- src/uiComponents/ExpertProfileEditPage/LocationSection.tsx
#130
- confirm 공통 ui로 추가
- confirm 안에 addToasts는 자유롭게 쓰셔도 됩니다.
Close #130
어떤 변경 사항이 있나요?
> Feat: confirm 공통 ui 추가

- src/components/Input/Input.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/uiComponents/ChatPage/InputField.tsx
#147 
빌드용 채팅페이지 코드 주석처리
#147 
어떤 변경 사항이 있나요?
> Chore: 빌드용 채팅페이지 코드 수정

- src/api/experts.ts
- src/api/services.ts
- src/config/types.ts
- src/pages/ExpertProfileEditPage.tsx
#139
-  api 코드 수정
- toast 타입 사라짐 이슈로 다시 추가
Close #139
어떤 변경 사항이 있나요?
> Refactor: 코드 리팩토링

- src/components/Header/Header.tsx
- src/pages/MyPage.tsx
- src/pages/UserEstimationPage.tsx
- src/styles/header.scss
> Refactor : Header 반응형레이아웃 1차 완료

- src/components/Button/MainBtn.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/IconButton/IconBtn.tsx
- src/components/Input/Input.tsx
- src/components/Input/NumberInput.tsx
- src/components/Textarea/Textarea.tsx
- src/pages/ChatListPage.tsx
#157 
멘토링 공통 추가 수정
#157 
어떤 변경 사항이 있나요?
> Fix: 멘토링 공통 영역 추가 수정

- src/components/Header/Header.tsx
- src/config/types.ts
- src/pages/CallbackPage.tsx
- src/pages/LoginPage.tsx
- src/pages/MainPage.tsx
- src/uiComponents/MainPage/Filming.tsx
- src/uiComponents/MainPage/Singer.tsx
- src/uiComponents/MainPage/Snapshot.tsx
- src/uiComponents/MainPage/WeddingMC.tsx
#161 
백엔드 요청 시 쿠키가 받아와지지 않아서 임시적으로 로그아웃 기능 수정
closes #161 
어떤 변경 사항이 있나요?
> Test : 개발 편의성을 위한 로그아웃 기능 임시 수정

- src/components/Header/Header.tsx
- src/pages/CallbackPage.tsx
- src/pages/MainPage.tsx
- src/styles/toastMessage.scss
#165 
로그인 및 로그아웃 시, 토스트 ui로 알림 띄움
closes #165 
어떤 변경 사항이 있나요?
> Feat : 로그인, 로그아웃 시 토스트 알림 띄움

- src/components/Header/Header.tsx
- src/styles/header.scss
#115 
- 알람추가
- 알람 아이콘 svg 파일 추가 
- 레이아웃 일부수정
- 공통 UI 링크 삭제 
- 반응형 제작 및 링크이동 수정
어떤 변경 사항이 있나요?
- [x] 새로운 기능 추가
> Refactor : 알람추가(feat.tosioB) 및 Header 수정

- src/api/experts.ts
- src/pages/ExpertProfileEditPage.tsx
- src/styles/ExpertProfileEditPage/main.scss
#169
- api 형태 변경 리팩토링
어떤 변경 사항이 있나요?
> Refactor: api 함수 변경

- src/api/experts.ts
- src/pages/ExpertProfileEditPage.tsx
- src/uiComponents/ExpertProfileEditPage/CareerSection.tsx
#169
- expert - post, get, patch 부분 데이터가 잘 받아와지는 것을 확인
어떤 변경 사항이 있나요?
> Fix: 전문가 프로필 페이지 api 데이터 확인 완료

- .gitignore
- package.json
- src/components/Header/Header.tsx
- src/pages/CallbackPage.tsx
- src/pages/MainPage.tsx
- src/uiComponents/MainPage/Filming.tsx
- src/uiComponents/MainPage/Singer.tsx
- src/uiComponents/MainPage/Snapshot.tsx
- src/uiComponents/MainPage/WeddingMC.tsx
#172 
- .env.development 와 .env.production 으로 파일 분리 필요!!
- npm run dev 시에는 개발모드로 열리고, build 시에는 production env를 사용해서 빌드가 됩니다.
closes #172 
어떤 변경 사항이 있나요?
> Chore : 개발 모드와 프로덕션 모드의 분리

- src/api/estimations.ts
- src/config/dummy.ts
- src/mocks/handlers.ts
- src/pages/Estimationlistpage.tsx
- src/pages/Expertlistpage.tsx
- src/store/expertListStore.ts
- src/uiComponents/Estimationlist/ExpertProfileModal.tsx
- src/uiComponents/Expertlist/ExpertModal.tsx
#175 
받은요청 api 연결 완료 받은견적 더미데이터 넣어놓기 
Close#175
어떤 변경 사항이 있나요?
> Fix:받은견적,받은요청api수정

- src/api/axiosInstance.ts
- src/components/Header/Header.tsx
- src/components/LoadingSpinner/LoadingSpinner.tsx
- src/pages/CallbackPage.tsx
- src/pages/LoginPage.tsx
- src/pages/MainPage.tsx
- src/styles/MainPage/main.scss
- src/styles/loadingspinner.scss
- src/uiComponents/MainPage/Singer.tsx
- src/uiComponents/MainPage/Snapshot.tsx
- src/uiComponents/MainPage/TabContentType.tsx
#177
AT 재발급 로직에서 에러 발생으로 인해 코드 수정
closes #177 
어떤 변경 사항이 있나요?
> Fix : AT 재발급 로직 수정

- src/pages/CallbackPage.tsx
#179 
- import 오류 수정
- 오타수정
- callbackpage.scss import부분 주석처리 
#179 
어떤 변경 사항이 있나요?
> Fix : (hotFix) CallbackPage import오류 수정

- src/pages/Estimationlistpage.tsx
- src/pages/Expertlistpage.tsx
- src/styles/Estimationpage/estimation.scss
- src/styles/Expertlistpage/expertlistpage.scss
- src/uiComponents/Estimationlist/ExpertProfileModal.tsx
- src/uiComponents/Expertlist/ExpertModal.tsx
#181 
받은요청과 받은견적부분 중복된 코드 확인후 리펙토링 했습니다. 그리고 로딩스피너 적용후 위치 정중앙으로 옮겼습니다.
close#181
어떤 변경 사항이 있나요?
> Refactor:받은요청,받은견적 리펙토링, 로딩스피너 위치 옮기기

- src/components/Header/Header.tsx
- src/styles/alarm.scss
- src/styles/header.scss
#115 
- 로그인 전 슬라이더 메뉴 레이아웃 일부수정
- 슬라이더 메뉴 투명도 조절
- 반응형 전 '전문가'영역 추가 -> 추후 프로필 이미지 모달로 넘어갈 예정
- 알람부분 - 컴포넌트형식으로 수정
- 알람모달 투명도 수정
어떤 변경 사항이 있나요?
> Design : UI 수정

- src/components/Header/Header.tsx
- src/pages/MainPage.tsx
#186 
헤더 전문가 버튼 변경 (호버 가능하도록 스타일 추가
유저에서 전문가 전환에 따른 toast ui 추가
closes #186 
어떤 변경 사항이 있나요?
> Feat : 유저 -> 전문가 전환 기능 추가

- src/pages/ExpertProfileEditPage.tsx
- src/styles/ExpertProfileEditPage/main.scss
- src/uiComponents/ExpertProfileEditPage/CareerSection.tsx
- src/uiComponents/ExpertProfileEditPage/LocationSection.tsx
- src/uiComponents/ExpertProfileEditPage/ProfileSection.tsx
- src/uiComponents/ExpertProfileEditPage/ServiceSection.tsx
#169
- 전문가 프로필 페이지 로딩 스피너 추가
- 레이아웃 부분 수정
- 코드 리팩토링
- ProfileSection-appeal 부분 완료 버튼 -> 화면 클릭시 profileData 상태에 담기게 변경
- 전문가 전환에 맞게 코드 연결
어떤 변경 사항이 있나요?
> Feat: 전문가 프로필 페이지 로딩 스피너 추가 및 레이아웃 부분 수정

- src/components/Header/Header.tsx
- src/components/LoadingSpinner/LoadingSpinner.tsx
- src/pages/CallbackPage.tsx
#189 
로딩 스피너 에러 코드 수정
closes #189 
어떤 변경 사항이 있나요?
> Fix : 로딩 스피너 에러 코드 수정

- src/pages/UserEstimationPage.tsx
#195 
Fix : UserEstimationPage scss파일 import 수정
close #195 
어떤 변경 사항이 있나요?
> Fix : UserEstimationPage scss파일 import 수정

- src/api/axiosInstance.ts
- src/pages/CallbackPage.tsx
- src/pages/LoginPage.tsx
- src/pages/MainPage.tsx
#122 
엑시오스 인터셉터에서 무한 요청가는 이슈 해결
closes #122 
어떤 변경 사항이 있나요?
> Fix : 엑시오스 무한 요청 수정

- src/pages/ExpertProfileEditPage.tsx
#198
- get api 불러오는 중 setIsLoading에 true로 수정
Close #198
어떤 변경 사항이 있나요?
> Fix: 버그 수정

- src/pages/ExpertProfileEditPage.tsx
- src/uiComponents/ExpertProfileEditPage/ProfileSection.tsx
#200
- 전문가 일 때 아닐 때에 대한 코드 분리 중 로딩 상태관리에서 제대로 분리 못한 곳을 수정
- 전문가 등록일 때 image src 태그 안 보이게 수정
Close #200
어떤 변경 사항이 있나요?
> Fix: 로딩 부분 버그 수정

- src/pages/Expertlistpage.tsx
- src/uiComponents/Estimationlist/ExpertProfileModal.tsx
- src/uiComponents/Expertlist/ExpertModal.tsx
#205 
견적보내기가 안된 이유를 찾았고 수정해서 이제 전문가가 견적을 보내면 유저가 전문가한테 견적을 받을 수 있습니다.
전문가가 받은 요청중에 삭제부분이 추가 되었습니다.
Close#(205)
어떤 변경 사항이 있나요?
> Feat, Fix:견적보내기API 수정, 받은요청 삭제 API 연결

- src/components/Header/Header.tsx
- src/pages/CallbackPage.tsx
#209 
AT 만료 시에 토큰 리프레시 되지 않는 현상애 대해 코드 수정
closes #209 
어떤 변경 사항이 있나요?
> Fix : AT refresh 안되는 현상 수정

- src/pages/ExpertProfileEditPage.tsx
#212
- loading 부분 견고하게 코드 수정 및 버그 수정
- prevClick 조건 코드 수정
Close #212
어떤 변경 사항이 있나요?
> Fix: loading, prevClick 버그 수정

- src/App.tsx
- src/components/Header/Header.tsx
- src/pages/ExpertProfileEditPage.tsx
- src/styles/header.scss
#214 
isExpert를 사용한 유저에서 전문가, 전문가에서 유저 전환 기능 
closes #214 
어떤 변경 사항이 있나요?
> Feat : 유저에서 전문가, 전문가에서 유저 전환 기능 생성

- src/api/reserve.ts
- src/pages/UserEstimationPage.tsx
> Fix : mock연결 해제

- package-lock.json
- package.json
- src/App.tsx
- src/components/Header/Header2.tsx
- src/layouts/CommonLayout.tsx
- src/pages/CallbackPage.tsx
- src/store/modeChangerStore.tsx
#225 
- 전역 상태 guest|user|expert 생성
- 전역 상태에 따른 header 구성 변경 및 수정
- 페이지 navigate 연결
closes #225 
어떤 변경 사항이 있나요?
> Feat : 전역 상태 guest|user|expert 생성 및 header 재구성

- src/components/Badge/ProfileBadge.tsx
- src/pages/Estimationlistpage.tsx
- src/pages/Expertlistpage.tsx
- src/store/estimationStore.ts
- src/styles/Estimationpage/estimation.scss
- src/uiComponents/Estimationlist/ExpertProfileModal.tsx
- src/uiComponents/Expertlist/ExpertModal.tsx
#230 
코드의 중복부분이랑, 영어로 나오는 부분 고쳤습니다.
Close#230
어떤 변경 사항이 있나요?
> Refactor: 코드리펙토링

- src/api/estimations.ts
- src/pages/CalenderPage.tsx
- src/styles/CalenderPage/main.scss
#204
- 페이지 레이아웃
- 날짜 클릭 시 해당 달에 맞는 일자가 나옴. + 해당 달 기준 전 달, 다음 달 보이는 일자는 gray로 구분
- api 연결
Close #204
어떤 변경 사항이 있나요?
> Design: 캘린더페이지 레이아웃

- src/components/Header/Header.tsx
- src/pages/CallbackPage.tsx
- src/pages/MyPage.tsx
#235, #236
- 전문가 여부에 따라 mode를 변경하여 먼저 보여주는 페이지를 분리함.
- 전문가 여부에 따라 보여지는 마이페이지를 다르게 분기 처리함. 
closes #236 closes #235 
어떤 변경 사항이 있나요?
> Feat : 전문가 여부에 따라 보이는 페이지 분리, 마이페이지 버튼 분기 처리

- src/pages/ExpertProfileEditPage.tsx
#234
- 전문가 프로필 등록 시 setMode('expert') 추가
- 이전 버튼 클릭 시 마이페이지로 이동
close #234
어떤 변경 사항이 있나요?
> Feat: 전문가 모드 및 이전 버튼 페이지 이동 주소 수정

- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/uiComponents/ChatPage/InputField.tsx
- src/utils/chatSocket.ts
#211 
채팅페이지 웹소켓 연결 중간저장2
어떤 변경 사항이 있나요?
> Feature: 채팅 웹소켓 연결 중간저장2

- src/api/estimations.ts
- src/api/reserve.ts
- src/config/types.ts
- src/pages/CalenderPage.tsx
- src/styles/CalenderPage/main.scss
#233
- api 받아오기 및 레이아웃 구성
- 로딩 스피너 추가
- 오늘 날짜로 다시 이동 버튼 추가
- api 네이밍 수정으로 api 폴더 > estimations.ts -> reserve.ts로 이동
- calender 타입 추가
close #233
어떤 변경 사항이 있나요?
> Feat: 캘린더페이지 api 데이터 가져오기

- src/store/useMessageStore.tsx
- src/styles/ChatPage/chatPage.scss
- src/uiComponents/ChatListPage/AllChats.tsx
- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/utils/chatSocket.ts
#211 
채팅페이지 웹소켓 중간저장3
어떤 변경 사항이 있나요?
> Feature: 채팅페이지 웹소켓 중간저장3

- package-lock.json
- src/App.tsx
- src/api/reserve.ts
- src/components/Button/MainBtn.tsx
- src/config/types.ts
- src/pages/ReservationPage.tsx
- src/pages/UserEstimationPage.tsx
- src/styles/UserEstimationPage/main.scss
- src/uiComponents/UserEstimationEdit/WeddingLocation.tsx
#217 
- 주석및 일부 코드 정리
- 버튼의 type 추가 ( 제출, 버튼, 리셋 타입 -> 기본값 : 'button')
-  견적서 관련 타입추가
- 견적서 관련 내용추가
어떤 변경 사항이 있나요?
> Feature/user estimation/#217

- src/components/Tab/Tab.tsx
- src/pages/MainPage.tsx
- src/styles/MainPage/main.scss
- src/styles/loadingspinner.scss
- src/uiComponents/MainPage/Singer.tsx
- src/uiComponents/MainPage/Snapshot.tsx
- src/uiComponents/MainPage/TabContentType.tsx
- src/uiComponents/MainPage/Video.tsx
- src/uiComponents/MainPage/WeddingMC.tsx
> Feat : main 페이지 전문가 목록 클릭 시, 상태에 따라 페이지 이동

- README.md
- src/config/dummy.ts
- src/mocks/handlers.ts
- src/pages/Estimationlistpage.tsx
- src/styles/Estimationpage/estimation.scss
- src/styles/Expertlistpage/expertModal.scss
- src/styles/Expertlistpage/expertlistpage.scss
#247 
받은견적, 받은요청, 견적보내기 버튼CSS 호버 내용 추가 해서 클릭하는 느낌 만들었습니다.
Close#247
어떤 변경 사항이 있나요?
> Design: 받은견적, 받은요청, 견적보내기 버튼 호버추가

- src/components/Badge/ProfileBadge.tsx
- src/pages/ChatPage.tsx
- src/uiComponents/ChatListPage/AllChats.tsx
- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/uiComponents/ChatPage/ExpertWrapper.tsx
#211 
채팅페이지 웹소켓 적용 중간저장4
어떤 변경 사항이 있나요?
> Feature: 채팅페이지 웹소켓 적용 중간저장4

- src/pages/CalenderPage.tsx
- src/styles/CalenderPage/detailCalender.scss
- src/styles/CalenderPage/main.scss
#241
close #241
어떤 변경 사항이 있나요?
> Design: 로딩 후 애니메이션 추가

- src/components/Header/Header.tsx
- src/styles/header.scss
#254 
- 멘토링 코멘트에 따른 수정
- 1개의 role=navigation태그 사용
- Link 태그 + button 컴포넌트 중복사용으로 a태그 중복
- 로그아웃버튼 클릭시 link태그로 링크이동이 아닌 onclick이벤트로 navigate('/') 함수 추가
어떤 변경 사항이 있나요?
> Refactor : 멘토링 코멘트에 따른 수정

- src/pages/ChatPage.tsx
- src/store/useMessageStore.tsx
- src/uiComponents/ChatListPage/AllChats.tsx
- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/uiComponents/ChatPage/ExpertWrapper.tsx
- src/utils/chatSocket.ts
#211 
채팅 페이지 웹소켓 중간저장5
어떤 변경 사항이 있나요?
> Feature: 채팅 페이지 웹소켓 중간저장5

- src/pages/UserEstimationPage.tsx
- src/uiComponents/UserEstimationEdit/WeddingLocation.tsx
#217 
- 견적요청서 API post요청 기능 추가
- 현재 location detail 데이터 추가하여 api 요청시 400번대 에러 발생 (현재 수정중)
어떤 변경 사항이 있나요?
> Feat : 견적요청서page post요청 기능 추가

- src/pages/Estimationlistpage.tsx
#260 
받은견적 채팅방 연결부분을 수정을 했습니다.
Close#(260)
어떤 변경 사항이 있나요?
> Fix:받은견적 채팅방 연결 수정

- src/pages/CalenderPage.tsx
- src/styles/CalenderPage/detailCalender.scss
- src/styles/CalenderPage/main.scss
- src/uiComponents/CalenderPage/DetailCalender.tsx
#258
- 코드 리팩토링
close #258
어떤 변경 사항이 있나요?
> Refactor: 캘린더 페이지 리팩토링

- src/components/Alarm/Alarm.tsx
- src/components/Input/NumberInput.tsx
- src/store/useAlarmStore.ts
- src/styles/ChatPage/chatPage.scss
- src/styles/common.scss
- src/uiComponents/ChatListPage/AllChats.tsx
- src/uiComponents/ChatListPage/chat.ts
- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/uiComponents/ChatPage/ExpertWrapper.tsx
- src/uiComponents/ChatPage/Modal/TransactionConfirmModal.tsx
- src/uiComponents/ChatPage/Modal/TransactionModal.tsx
- src/utils/alarmSocket.ts
- src/utils/chatFormatDate.ts
#211 
채팅 페이지 웹소켓 연결 중간저장6
어떤 변경 사항이 있나요?
> Feature: 채팅 페이지 웹소켓 연결 중간저장6

- src/api/axiosInstance.ts
- src/components/Header/Header.tsx
- src/components/Header/HeaderOld.tsx
- src/pages/CallbackPage.tsx
- src/pages/ChatPage.tsx
- src/pages/MainPage.tsx
- src/store/loginToastStateStore.ts
- src/store/modeChangerStore.tsx
- src/store/useLoginProviderStore.tsx
- src/store/useUserStateStore.tsx
- src/styles/header.scss
- src/uiComponents/ChatListPage/AllChats.tsx
- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
#266 
소셜 로그인 sessionStorage 저장으로 코드 변경
closes #266 
어떤 변경 사항이 있나요?
> Refactor : 소셜 로그인 sessionStorage 저장으로 코드 변경

- src/components/Alarm/Alarm.tsx
- src/pages/MainPage.tsx
- src/styles/ChatPage/chatPage.scss
- src/uiComponents/ChatListPage/chat.ts
- src/uiComponents/ChatPage/ChatContainer.tsx
- src/uiComponents/ChatPage/ExpertWrapper.tsx
- src/uiComponents/ChatPage/Modal/TransactionConfirmModal.tsx
- src/uiComponents/ChatPage/Modal/TransactionModal.tsx
- src/utils/alarmSocket.ts
#211 
채팅 페이지 웹소켓 연결 중간저장7
어떤 변경 사항이 있나요?
> Feature: 채팅 페이지 웹소켓 연결 중간저장7

- src/api/axiosInstance.ts
- src/pages/CallbackPage.tsx
- src/store/useUserStateStore.tsx
#272 
불필요한 코드 삭제 및 정리
어떤 변경 사항이 있나요?
> Style : 콘솔 로그 등 불필요한 코드 정리

- src/components/Alarm/Alarm.tsx
- src/store/useAlarmStore.ts
- src/uiComponents/ChatPage/ExpertWrapper.tsx
- src/uiComponents/ChatPage/Modal/TransactionConfirmModal.tsx
- src/uiComponents/ChatPage/Modal/TransactionModal.tsx
#211 
채팅/알람 웹소켓 페이지 작업
알람 개별 읽음 처리 바로 삭제 기능 추가
거래 요청 에러 수정
예약 완료 에러 수정
#211 
어떤 변경 사항이 있나요?
- [] 새로운 기능 추가
> Feature: 웹소켓 채팅/알람 페이지 작업

- src/pages/Expertlistpage.tsx
- src/uiComponents/Expertlist/ExpertModal.tsx
#279 
closes #279 
어떤 변경 사항이 있나요?
> Design : 전문가 정보를 전문가에게 입력받지 않고 props로 넘겨서 전달해주기

- src/pages/ExpertProfileEditPage.tsx
- src/styles/ExpertProfileEditPage/main.scss
#278
- 전문가 프로필 페이지에서 기존에 사용했던 로딩 스피너는 제거하고 스켈레톤 ui로 변경
- patch, post 시 response로 받아오는 데이터가 undefined가 아닐 때 동작할 수 있게 수정
close #278
어떤 변경 사항이 있나요?
> Feat: 스켈레톤 Ui 추가

- src/pages/MainPage.tsx
> Fix : 유저 상태 전환 오류 에러 해결

- src/pages/ExpertProfileEditPage.tsx
#286
- console.log() 제거
close #286
어떤 변경 사항이 있나요?
> Style: 콘솔 로그 제거

- src/api/axiosInstance.ts
- src/components/Header/Header.tsx
- src/pages/CallbackPage.tsx
- src/pages/MainPage.tsx
> Style : 콘솔 로그 주석 처리

- src/components/Alarm/Alarm.tsx
#293 
알림 전문가/고객 필터링 작업
#293 
어떤 변경 사항이 있나요?
> Fix: 알림 전문가/고객 필터링 작업

- README.md
> chore : readme 프로젝트 구조 수정

- src/config/types.ts
- src/pages/ReservationPage.tsx
- src/uiComponents/MyPage/Reservation/ReservationContent.tsx
- src/uiComponents/MyPage/Reservation/UserReviewEdit/ReviewEdit.tsx
#298 
- user mode에 따른 버튼 UI 변경완료
- 리스트에서 고객이름만 출력되는 문제 수정
#298 
어떤 변경 사항이 있나요?
> Refactor : 유저,전문가 상태에 따른 props 추가

- src/styles/CalenderPage/detailCalender.scss
#306
- 캘린더 모달에서 '서비스 완료' 상태일 때 scss 변하지 않는 에러 수정
close #306
어떤 변경 사항이 있나요?
> Fix: scss 수정

- src/components/Input/NumberInput.tsx
- src/pages/Estimationlistpage.tsx
- src/pages/Expertlistpage.tsx
> Fix받은요청,받은견적 mode따라 페이지 접근제한

- src/pages/ExpertProfileEditPage.tsx
- src/uiComponents/ExpertProfileEditPage/LocationSection.tsx
#312
- 잔오류 처리
close #312
어떤 변경 사항이 있나요?
> Fix: 에러 수정

- src/api/reserve.ts
- src/config/types.ts
- src/pages/ReservationPage.tsx
- src/uiComponents/MyPage/Reservation/EstimationConfirm/EstimationConfirm.tsx
- src/uiComponents/MyPage/Reservation/ReservationContent.tsx
- src/utils/serviceKorean.tsx
- src/utils/statusKorean.tsx
#305 
견적서 확인부분 API 추가 (웨딩홀 정보 및 견적(예약 정보) 
견적서 확인서 부분  일부수정했습니다. CSS는 진행 일단 후순위
close #305  
어떤 변경 사항이 있나요?
- [x] 새로운 기능 추가
- [x] 버그 수정
- [x] 코드 리팩토링
- [x] 파일 혹은 폴더명 수정
- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
> Refactor : confirmPage API호출 및 기능 일부 수정

- src/api/reserve.ts
- src/config/types.ts
- src/styles/MyPage/EstimationConfirm.scss
- src/uiComponents/MyPage/Reservation/EstimationConfirm/EstimationConfirm.tsx
- src/uiComponents/MyPage/Reservation/ReservationContent.tsx
#319 
- Expert모드에서 Mypage-예약리스트-견적서 확인에서  전문가가 예약 상태를 변경할수 있는 예약취소및완료 Api 추가
- 예약 확정상태에서 전문가는 예약을 취소 및 서비스 완료를 할 수 있으며 예약 상태가 변경됨 (고객은 할수 없음)
- 각 상태를 변경하면 toast도 화면에 표시됨 
- 견적확인서 CSS 변경
#319 
어떤 변경 사항이 있나요?
> Feat : Expert모드 견적Confirm에서 예약취소및완료 Api 추가

- src/pages/Estimationlistpage.tsx
- src/pages/Expertlistpage.tsx
- src/uiComponents/Estimationlist/ExpertProfileModal.tsx
- src/uiComponents/Expertlist/ExpertModal.tsx
> Refactor:console,주석제거

- src/pages/ChatPage.tsx
- src/uiComponents/ChatListPage/ChatList.tsx
- src/uiComponents/ChatPage/ChatRoom.tsx
- src/uiComponents/ChatPage/ExpertWrapper.tsx
- src/utils/alarmSocket.ts
- src/utils/chatSocket.ts
#330 
채팅/알람 페이지 콘솔로그 주석 처리
어떤 변경 사항이 있나요?
> fix: 채팅/알람 페이지 콘솔로그 주석 처리

- README.md
> Chore : 리드미 트러블 슈팅 추가

- README.md
> Chore : 업데이트 README.md

- README.md
#337
- 리드미 수정
close #337
어떤 변경 사항이 있나요?
> Chore: README 수정

- src/uiComponents/ChatPage/ChatRoom.tsx
#339 
채팅 안읽음 버그 수정
#339 
어떤 변경 사항이 있나요?
> fix: 채팅 안읽음 버그 수정

- README.md
리드미 트러블 슈팅 링크 추가
어떤 변경 사항이 있나요?
> Feature: 리드미 트러블 슈팅 링크 추가

- src/pages/UserEstimationPage.tsx
- src/styles/UserEstimationPage/main.scss
#343 
Design : UserEstimationPage 일부UI 및 에러메세지 수정
close #343 
어떤 변경 사항이 있나요?
> Design : UserEstimationPage 일부UI 및 에러메세지 UI 수정
